version: '3.9'

services:
  postgres-template:
    container_name: postgres
    image: postgres:latest
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./volume/data:/var/lib/postgresql/data
    restart: unless-stopped



volumes:
  postgres-volume: